# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class main(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1032, 840)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 70, 1031, 771))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.productTable = QtWidgets.QTableWidget(self.layoutWidget)
        self.productTable.setObjectName("productTable")
        self.productTable.setColumnCount(0)
        self.productTable.setRowCount(0)
        self.verticalLayout.addWidget(self.productTable)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.insuranceTable = QtWidgets.QTableWidget(self.layoutWidget)
        self.insuranceTable.setObjectName("insuranceTable")
        self.insuranceTable.setColumnCount(0)
        self.insuranceTable.setRowCount(0)
        self.gridLayout.addWidget(self.insuranceTable, 2, 0, 1, 1)
        self.fundTable = QtWidgets.QTableWidget(self.layoutWidget)
        self.fundTable.setObjectName("fundTable")
        self.fundTable.setColumnCount(0)
        self.fundTable.setRowCount(0)
        self.gridLayout.addWidget(self.fundTable, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 2)
        self.cardTable = QtWidgets.QTableWidget(self.layoutWidget)
        self.cardTable.setObjectName("cardTable")
        self.cardTable.setColumnCount(0)
        self.cardTable.setRowCount(0)
        self.gridLayout.addWidget(self.cardTable, 4, 0, 1, 1)
        self.financesTable = QtWidgets.QTableWidget(self.layoutWidget)
        self.financesTable.setObjectName("financesTable")
        self.financesTable.setColumnCount(0)
        self.financesTable.setRowCount(0)
        self.gridLayout.addWidget(self.financesTable, 4, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 20, 821, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.checkBtn.setObjectName("checkBtn")
        self.horizontalLayout_3.addWidget(self.checkBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.manageBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.manageBtn.setObjectName("manageBtn")
        self.horizontalLayout_3.addWidget(self.manageBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.showBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.showBtn.setObjectName("showBtn")
        self.horizontalLayout_3.addWidget(self.showBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.updateBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.updateBtn.setObjectName("updateBtn")
        self.horizontalLayout_3.addWidget(self.updateBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "主界面"))
        self.label.setText(_translate("Form", "总表"))
        self.label_2.setText(_translate("Form", "保险"))
        self.label_3.setText(_translate("Form", "基金"))
        self.label_4.setText(_translate("Form", "银行卡"))
        self.label_5.setText(_translate("Form", "理财产品"))
        self.checkBtn.setText(_translate("Form", "查看拥有产品"))
        self.manageBtn.setText(_translate("Form", "办理业务"))
        self.showBtn.setText(_translate("Form", "可视化展示"))
        self.updateBtn.setText(_translate("Form", "修改信息"))
