# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class manage(object):
    def setupUi(self, Form):
        Form.setObjectName("业务办理")
        Form.resize(1122, 858)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(11, 17, 1091, 761))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.fundEdit = QtWidgets.QLineEdit(self.widget)
        self.fundEdit.setObjectName("fundEdit")
        self.gridLayout.addWidget(self.fundEdit, 0, 5, 1, 1)
        self.fundNum = QtWidgets.QSpinBox(self.widget)
        self.fundNum.setObjectName("fundNum")
        self.gridLayout.addWidget(self.fundNum, 0, 6, 1, 1)
        self.fundBtn = QtWidgets.QPushButton(self.widget)
        self.fundBtn.setObjectName("fundBtn")
        self.gridLayout.addWidget(self.fundBtn, 0, 7, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.layoutWidget = QtWidgets.QWidget(self.widget1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.cardKindEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.cardKindEdit.setObjectName("cardKindEdit")
        self.gridLayout_2.addWidget(self.cardKindEdit, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.cardEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.cardEdit.setObjectName("cardEdit")
        self.gridLayout_2.addWidget(self.cardEdit, 1, 1, 1, 1)
        self.cardBtn = QtWidgets.QPushButton(self.widget1)
        self.cardBtn.setGeometry(QtCore.QRect(180, 240, 93, 28))
        self.cardBtn.setObjectName("cardBtn")
        self.gridLayout.addWidget(self.widget1, 1, 0, 1, 4)
        self.fundTable = QtWidgets.QTableWidget(self.widget)
        self.fundTable.setObjectName("fundTable")
        self.fundTable.setColumnCount(0)
        self.fundTable.setRowCount(0)
        self.gridLayout.addWidget(self.fundTable, 1, 4, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.insuranceEdit = QtWidgets.QLineEdit(self.widget)
        self.insuranceEdit.setObjectName("insuranceEdit")
        self.gridLayout.addWidget(self.insuranceEdit, 2, 1, 1, 1)
        self.insuranceNum = QtWidgets.QSpinBox(self.widget)
        self.insuranceNum.setObjectName("insuranceNum")
        self.gridLayout.addWidget(self.insuranceNum, 2, 2, 1, 1)
        self.insuranceBtn = QtWidgets.QPushButton(self.widget)
        self.insuranceBtn.setObjectName("insuranceBtn")
        self.gridLayout.addWidget(self.insuranceBtn, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 4, 1, 1)
        self.financeEdit = QtWidgets.QLineEdit(self.widget)
        self.financeEdit.setObjectName("financeEdit")
        self.gridLayout.addWidget(self.financeEdit, 2, 5, 1, 1)
        self.financesNum = QtWidgets.QSpinBox(self.widget)
        self.financesNum.setObjectName("financesNum")
        self.gridLayout.addWidget(self.financesNum, 2, 6, 1, 1)
        self.financeBtn = QtWidgets.QPushButton(self.widget)
        self.financeBtn.setObjectName("financeBtn")
        self.gridLayout.addWidget(self.financeBtn, 2, 7, 1, 1)
        self.insuranceTable = QtWidgets.QTableWidget(self.widget)
        self.insuranceTable.setObjectName("insuranceTable")
        self.insuranceTable.setColumnCount(0)
        self.insuranceTable.setRowCount(0)
        self.gridLayout.addWidget(self.insuranceTable, 3, 0, 1, 4)
        self.financesTable = QtWidgets.QTableWidget(self.widget)
        self.financesTable.setObjectName("financesTable")
        self.financesTable.setColumnCount(0)
        self.financesTable.setRowCount(0)
        self.gridLayout.addWidget(self.financesTable, 3, 4, 1, 4)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "业务办理"))
        self.label_2.setText(_translate("Form", "基金"))
        self.fundBtn.setText(_translate("Form", "购买"))
        self.label_5.setText(_translate("Form", "类型"))
        self.label_6.setText(_translate("Form", "卡号"))
        self.cardBtn.setText(_translate("Form", "办理"))
        self.label_3.setText(_translate("Form", "保险"))
        self.insuranceBtn.setText(_translate("Form", "购买"))
        self.label_4.setText(_translate("Form", "理财产品"))
        self.financeBtn.setText(_translate("Form", "购买"))
        self.label.setText(_translate("Form", "银行卡"))

