# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class update(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(736, 675)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 150, 271, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.account = QtWidgets.QLabel(self.layoutWidget)
        self.account.setObjectName("account")
        self.gridLayout.addWidget(self.account, 0, 0, 1, 1)
        self.old_account = QtWidgets.QLineEdit(self.layoutWidget)
        self.old_account.setObjectName("old_account")
        self.gridLayout.addWidget(self.old_account, 0, 1, 1, 1)
        self.name = QtWidgets.QLabel(self.layoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 1)
        self.old_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.old_name.setObjectName("old_name")
        self.gridLayout.addWidget(self.old_name, 1, 1, 1, 1)
        self.email = QtWidgets.QLabel(self.layoutWidget)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 2, 0, 1, 1)
        self.old_email = QtWidgets.QLineEdit(self.layoutWidget)
        self.old_email.setObjectName("old_email")
        self.gridLayout.addWidget(self.old_email, 2, 1, 1, 1)
        self.cardId = QtWidgets.QLabel(self.layoutWidget)
        self.cardId.setObjectName("cardId")
        self.gridLayout.addWidget(self.cardId, 3, 0, 1, 1)
        self.old_cardNum = QtWidgets.QLineEdit(self.layoutWidget)
        self.old_cardNum.setObjectName("old_cardNum")
        self.gridLayout.addWidget(self.old_cardNum, 3, 1, 1, 1)
        self.phone = QtWidgets.QLabel(self.layoutWidget)
        self.phone.setObjectName("phone")
        self.gridLayout.addWidget(self.phone, 4, 0, 1, 1)
        self.old_phone = QtWidgets.QLineEdit(self.layoutWidget)
        self.old_phone.setObjectName("old_phone")
        self.gridLayout.addWidget(self.old_phone, 4, 1, 1, 1)
        self.password = QtWidgets.QLabel(self.layoutWidget)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 5, 0, 1, 1)
        self.old_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.old_password.setObjectName("old_password")
        self.gridLayout.addWidget(self.old_password, 5, 1, 1, 1)
        self.submit = QtWidgets.QPushButton(Form)
        self.submit.setGeometry(QtCore.QRect(300, 430, 93, 28))
        self.submit.setObjectName("submit")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(370, 150, 271, 241))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.account_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.account_2.setObjectName("account_2")
        self.gridLayout_2.addWidget(self.account_2, 0, 0, 1, 1)
        self.new_account = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.new_account.setObjectName("new_account")
        self.gridLayout_2.addWidget(self.new_account, 0, 1, 1, 1)
        self.name_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.name_2.setObjectName("name_2")
        self.gridLayout_2.addWidget(self.name_2, 1, 0, 1, 1)
        self.new_name = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.new_name.setObjectName("new_name")
        self.gridLayout_2.addWidget(self.new_name, 1, 1, 1, 1)
        self.email_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.email_2.setObjectName("email_2")
        self.gridLayout_2.addWidget(self.email_2, 2, 0, 1, 1)
        self.new_email = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.new_email.setObjectName("new_email")
        self.gridLayout_2.addWidget(self.new_email, 2, 1, 1, 1)
        self.cardId_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.cardId_2.setObjectName("cardId_2")
        self.gridLayout_2.addWidget(self.cardId_2, 3, 0, 1, 1)
        self.new_cardNum = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.new_cardNum.setObjectName("new_cardNum")
        self.gridLayout_2.addWidget(self.new_cardNum, 3, 1, 1, 1)
        self.phone_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.phone_2.setObjectName("phone_2")
        self.gridLayout_2.addWidget(self.phone_2, 4, 0, 1, 1)
        self.new_phone = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.new_phone.setObjectName("new_phone")
        self.gridLayout_2.addWidget(self.new_phone, 4, 1, 1, 1)
        self.password_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.password_2.setObjectName("password_2")
        self.gridLayout_2.addWidget(self.password_2, 5, 0, 1, 1)
        self.new_password = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.new_password.setObjectName("new_password")
        self.gridLayout_2.addWidget(self.new_password, 5, 1, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(50, 110, 641, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "修改"))
        self.account.setText(_translate("Form", "账号"))
        self.name.setText(_translate("Form", "名字"))
        self.email.setText(_translate("Form", "邮箱"))
        self.cardId.setText(_translate("Form", "卡号"))
        self.phone.setText(_translate("Form", "手机"))
        self.password.setText(_translate("Form", "密码"))
        self.submit.setText(_translate("Form", "提交"))
        self.account_2.setText(_translate("Form", "账号"))
        self.name_2.setText(_translate("Form", "名字"))
        self.email_2.setText(_translate("Form", "邮箱"))
        self.cardId_2.setText(_translate("Form", "卡号"))
        self.phone_2.setText(_translate("Form", "手机"))
        self.password_2.setText(_translate("Form", "密码"))
        self.label.setText(_translate("Form", "旧信息"))
        self.label_2.setText(_translate("Form", "新信息"))
